import React, { useState, useEffect } from 'react';

function Profile({ userEmail }) {
    const [userData, setUserData] = useState(null);
    const [careerData, setCareerData] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchProfileData = async () => {
            setLoading(true);
            try {
                // Fetch basic user data (using dashboard endpoint for simplicity)
                const userRes = await fetch(`/dashboard/${userEmail}`);
                if (userRes.ok) {
                    const data = await userRes.json();
                    setUserData(data);
                }

                // Fetch Career Matches
                const careerRes = await fetch(`/skill/career/${userEmail}`);
                if (careerRes.ok) {
                    const data = await careerRes.json();
                    setCareerData(data);
                }

            } catch (error) {
                console.error("Failed to fetch profile data", error);
            } finally {
                setLoading(false);
            }
        };

        if (userEmail) {
            fetchProfileData();
        }
    }, [userEmail]);

    const handleGeneratePortfolio = () => {
        if (!userData || !careerData) return;

        // Simulate Portfolio Generation
        const skills = careerData.matches.length > 0
            ? `Top Career Matches:\n${careerData.matches.map(m => `- ${m.role} (${m.match_score}%)`).join('\n')}`
            : "Skills still developing.";

        const content = `
PORTFOLIO: ${userData.user.name}
Email: ${userData.user.email}
Generated by: Learning Buddy AI
--------------------------------------------------

SUMMARY
Dedicated learner with ${userData.stats.total_hours} hours of study time committed.
Completed ${userData.stats.completed} courses with an average score of ${userData.stats.average_score}.

SKILLS & CAREER FIT
${skills}

COURSES COMPLETED
${userData.courses.filter(c => c.status === 'Lulus').map(c => `- ${c.title}`).join('\n')}

--------------------------------------------------
Ready for new opportunities!
`;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Portfolio-${userData.user.name.replace(/\s+/g, '_')}.txt`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
    };

    if (loading) {
        return (
            <div className="flex justify-center items-center h-64">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
            </div>
        );
    }

    if (!userData) {
        return <div className="text-center py-10 text-red-500">Failed to load profile.</div>;
    }

    return (
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            {/* User Info Card */}
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-700 p-8 mb-8 flex flex-col md:flex-row items-center md:items-start gap-6">
                <img
                    src={userData.user.avatar}
                    alt={userData.user.name}
                    className="w-24 h-24 rounded-full border-4 border-gray-50 dark:border-gray-700 shadow-md"
                />
                <div className="text-center md:text-left flex-grow">
                    <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">{userData.user.name}</h1>
                    <p className="text-gray-500 dark:text-gray-400 mb-4">{userData.user.email}</p>
                    <div className="flex flex-wrap justify-center md:justify-start gap-3">
                        <span className="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm font-medium">
                            {userData.stats.completed} Kursus Selesai
                        </span>
                        <span className="px-3 py-1 bg-purple-100 text-purple-700 rounded-full text-sm font-medium">
                            {userData.stats.total_hours} Jam Belajar
                        </span>
                    </div>
                </div>
                <button
                    onClick={handleGeneratePortfolio}
                    className="px-6 py-3 bg-gray-900 hover:bg-gray-800 dark:bg-white dark:hover:bg-gray-100 text-white dark:text-gray-900 font-bold rounded-xl transition-all shadow-lg transform hover:-translate-y-0.5 flex items-center gap-2"
                >
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download Portfolio
                </button>
            </div>

            {/* Badges Section (Gamification) */}
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6 flex items-center gap-2">
                <span>Achievements 🏆</span>
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
                {/* Badge: Fast Learner (5+ Courses) */}
                <div className={`p-4 rounded-xl border ${userData.stats.completed >= 5 ? 'bg-yellow-50 border-yellow-200' : 'bg-gray-50 border-gray-100 opacity-50 grayscale'}`}>
                    <div className="text-4xl mb-2">🚀</div>
                    <div className="font-bold text-gray-900 dark:text-gray-800">Fast Learner</div>
                    <div className="text-xs text-gray-500">Selesaikan 5 Kursus</div>
                </div>
                {/* Badge: Dedicated (50+ Hours) */}
                <div className={`p-4 rounded-xl border ${userData.stats.total_hours >= 50 ? 'bg-purple-50 border-purple-200' : 'bg-gray-50 border-gray-100 opacity-50 grayscale'}`}>
                    <div className="text-4xl mb-2">🔥</div>
                    <div className="font-bold text-gray-900 dark:text-gray-800">Dedicated</div>
                    <div className="text-xs text-gray-500">50+ Jam Belajar</div>
                </div>
                {/* Badge: Top Performer (Avg Score > 90) */}
                <div className={`p-4 rounded-xl border ${userData.stats.average_score >= 90 ? 'bg-green-50 border-green-200' : 'bg-gray-50 border-gray-100 opacity-50 grayscale'}`}>
                    <div className="text-4xl mb-2">🌟</div>
                    <div className="font-bold text-gray-900 dark:text-gray-800">Top Performer</div>
                    <div className="text-xs text-gray-500">Nilai Rata-rata 90+</div>
                </div>
                {/* Badge: Tech Enthusiast (Any Skill > 80) */}
                <div className={`p-4 rounded-xl border ${careerData?.matches?.some(m => m.match_score > 80) ? 'bg-blue-50 border-blue-200' : 'bg-gray-50 border-gray-100 opacity-50 grayscale'}`}>
                    <div className="text-4xl mb-2">💻</div>
                    <div className="font-bold text-gray-900 dark:text-gray-800">Tech Enthusiast</div>
                    <div className="text-xs text-gray-500">Cocok dengan Karir Tech</div>
                </div>
            </div>

            {/* Career Matcher Section */}
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">Career Matcher AI ✨</h2>

            {!careerData || careerData.matches.length === 0 ? (
                <div className="bg-white dark:bg-gray-800 rounded-xl p-8 text-center text-gray-500 border border-dashed border-gray-300">
                    <p>Selesaikan lebih banyak kursus untuk melihat rekomendasi karir Anda.</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {careerData.matches.map((role, index) => (
                        <div key={index} className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm border border-gray-100 dark:border-gray-700 hover:shadow-md transition-shadow">
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h3 className="text-xl font-bold text-gray-900 dark:text-white">{role.role}</h3>
                                    <p className="text-sm text-gray-500 mt-1">{role.description}</p>
                                </div>
                                <div className="w-12 h-12 rounded-full flex items-center justify-center font-bold text-sm"
                                    style={{
                                        backgroundColor: role.match_score >= 80 ? '#ecfdf5' : role.match_score >= 50 ? '#eff6ff' : '#fff7ed',
                                        color: role.match_score >= 80 ? '#059669' : role.match_score >= 50 ? '#2563eb' : '#d97706'
                                    }}>
                                    {role.match_score}%
                                </div>
                            </div>

                            {/* Progress Bar */}
                            <div className="w-full bg-gray-100 dark:bg-gray-700 rounded-full h-2 mb-4">
                                <div
                                    className={`h-2 rounded-full transition-all duration-1000 ${role.match_score >= 80 ? 'bg-green-500' : role.match_score >= 50 ? 'bg-blue-500' : 'bg-orange-500'
                                        }`}
                                    style={{ width: `${role.match_score}%` }}
                                ></div>
                            </div>

                            <div className="flex justify-between text-xs text-gray-500">
                                <span>{role.skills_matched} dari {role.total_skills_required} skill terpenuhi</span>
                                <span>{role.match_score >= 80 ? 'Sangat Cocok' : 'Potensial'}</span>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}

export default Profile;
